version: '3.9'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: pokedex
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
    ports:
      - '3307:3306'

#  pokedex:
#    container_name: pokedex
#    restart: always
#    build:
#      context: .
#    ports:
#      - '8080:8080'
#    environment:
#      - SPRING_PROFILES_ACTIVE=
#    depends_on:
#      - mysqldb