version: '3'
services:
  mysql:
    container_name: mysqldb
    image: mysql:8
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_DATABASE=pokedex
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    command: ["--default-authentication-plugin=mysql_native_password"]

  java:
    container_name: pokedex
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=
      - DATABASE_HOST=mysqldb
      - DATABASE_PORT=3306
      - DATABASE_NAME=pokedex
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
    depends_on:
      - mysqldb